# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
      fos_userbundle:
        id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #main:
            #pattern: ^/
            #form_login:
            #    provider: fos_userbundle
            #    csrf_token_generator: security.csrf.token_manager
            #logout:       true
            #anonymous:    true
        bauth:
          pattern: ^/secret/basic_auth
          http_basic: ~
          stateless: true
          provider: fos_userbundle

        oauth:
          pattern:    ^/secret/oauth
          fos_oauth:  true
          stateless:  true
          anonymous:  false

        jwt:
          pattern: ^/secret/jwt
          stateless: true
          provider: fos_userbundle
          guard:
            authenticators:
              - lexik_jwt_authentication.jwt_token_authenticator
# ----
        oauth_token:
          pattern:    ^/oauth/v2/token
          security:   false
        oauth_authorize:
          pattern:    ^/oauth/v2/auth
          # Add your favorite authentication process here:
          form_login:
            provider: fos_userbundle
            check_path: /oauth/v2/auth/login_check
            login_path: /oauth/v2/auth/login
          anonymous: true
# -----
        jwt_login:
          pattern: ^/jwt/login
          stateless: true
          anonymous: true
          form_login:
            check_path: /jwt/login_check
            success_handler:          lexik_jwt_authentication.handler.authentication_success
            failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            require_previous_session: false

    access_control:
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/jwt/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

      - { path: ^/secret/basic_auth, role: ROLE_ADMIN }
      - { path: ^/secret/oauth, role: IS_AUTHENTICATED_FULLY }
      - { path: ^/secret/jwt, role: IS_AUTHENTICATED_FULLY }
